apiVersion: apps/v1
kind: Deployment
metadata:
  name: staff-service
  namespace: test
spec:
  selector:
    matchLabels:
      app: staff-service
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: staff-service
    spec:
      containers:
      - name: staff-service
        image: ianmward/istio-fleetman-staff-service:6
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources: {}
      - env:
        - name: mcgw_api_gateway_user
          value: Administrator
        - name: mcgw_ports_http
          value: "7070"
        - name: mcgw_downloads_apis
          value: nodetours
        - name: mcgw_api_gateway_password
          value: manage
        - name: mcgw_api_gateway_url
          value: http://api-gateway-service:5555
        image: harbor.aks.au-poc.com/library/softwareag/microgateway-trial:10.5.0.2
        imagePullPolicy: IfNotPresent
        name: softwareag-staff-service-sidecar
        ports:
        - containerPort: 7070
          protocol: TCP
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-staff-service
  namespace: test
  labels:
    app: staff-service
    service: fleetman-staff-service
spec:
  selector:
    app: staff-service
  ports:
    - name: http
      port: 8080
      targetPort: 7070
  type: NodePort
